name: Deploy Backend (Cloudflare Workers)

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Check wrangler config
        run: |
          if [ ! -f wrangler.toml ]; then
            echo "Missing wrangler.toml. Copy from wrangler.toml.example and set IDs." 1>&2
            exit 1
          fi

      - name: Publish with Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy
          workingDirectory: backend

